/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        cb: {
          bg: '#f7f9fc',
          surface: '#ffffff',
          'surface-nested': '#f8fafc',
          'surface-hover': '#f1f5f9',
          border: '#e2e8f0',
          'border-subtle': '#f1f5f9',
          'border-strong': '#cbd5e1',
          text: '#172033',
          'text-secondary': '#475569',
          muted: '#64748b',
          primary: '#2563eb',
          'primary-hover': '#1d4ed8',
          'primary-subtle': '#eff6ff',
          'primary-border': '#bfdbfe',
          success: '#10b981',
          'success-subtle': '#ecfdf5',
          'success-border': '#a7f3d0',
          warning: '#f59e0b',
          'warning-subtle': '#fffbeb',
          'warning-border': '#fde68a',
          critical: '#ef4444',
          'critical-subtle': '#fef2f2',
          'critical-border': '#fecaca',
          accent: '#4f46e5',
        },
        bg: '#f7f9fc',
        panel: '#ffffff',
        border: '#e2e8f0',
        textPrimary: '#172033',
        muted: '#64748b',
        accent: '#2563eb',
        danger: '#ef4444',
        warn: '#f59e0b',
        hit: '#10b981',
      },
      borderRadius: {
        'cb-xs': '0.25rem',
        'cb-sm': '0.375rem',
        'cb-md': '0.5rem',
        'cb-lg': '0.75rem',
        'cb-xl': '1rem',
      },
      boxShadow: {
        'cb-xs': '0 1px 2px 0 rgba(15, 23, 42, 0.04)',
        'cb-sm': '0 1px 3px 0 rgba(15, 23, 42, 0.06), 0 1px 2px -1px rgba(15, 23, 42, 0.04)',
        'cb-md': '0 4px 6px -1px rgba(15, 23, 42, 0.06), 0 2px 4px -2px rgba(15, 23, 42, 0.04)',
        'cb-lg': '0 10px 15px -3px rgba(15, 23, 42, 0.07), 0 4px 6px -4px rgba(15, 23, 42, 0.03)',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      }
    },
  },
  plugins: [],
}
